[package]
name = "switch_context"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tui = "0.18"
crossterm = "0.23"
clap = { version = "3.0", features = ["derive"] }
